audio: Add missing definitions
device/explay/fog2/hardware/audio/audio_hw.c: In function 'select_mode':
device/explay/fog2/hardware/audio/audio_hw.c:590:59: error: 'AUDIO_MODE_MODE_FACTORY_TEST' undeclared (first use in this function)
     if (adev->mode == AUDIO_MODE_IN_CALL || adev->mode == AUDIO_MODE_MODE_FACTORY_TEST) {
                                                           ^
device/explay/fog2/hardware/audio/audio_hw.c:590:59: note: each undeclared identifier is reported only once for each function it appears in
device/explay/fog2/hardware/audio/audio_hw.c:635:23: error: 'AUDIO_MODE_FM' undeclared (first use in this function)
     if (adev->mode == AUDIO_MODE_FM) {
                       ^
device/explay/fog2/hardware/audio/audio_hw.c:1102:33: error: 'AUDIO_PARAMETER_RAW_DATA_OUT' undeclared (first use in this function)
  ret = str_parms_get_str(parms, AUDIO_PARAMETER_RAW_DATA_OUT, value, sizeof(value));
                                 ^
device/explay/fog2/hardware/audio/audio_hw.c:2451:17: error: 'AUDIO_DEVICE_IN_AF' undeclared (first use in this function)
  if (devices == AUDIO_DEVICE_IN_AF) {
                 ^